apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-template
  labels:
    app: svc-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-template
  template:
    metadata:
      labels:
        app: svc-template
    spec:
      volumes:
        - name: svc-template-configmap
          configMap:
            name: svc-template-configmap
      containers:
        - name: main
          image: loads/svc-template:develop
          imagePullPolicy: Always
          command:
            - /app/main
            - server
          volumeMounts:
            - name: svc-template-configmap
              mountPath: "/app/config"

