apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  config.yaml: |
    # https://goframe.org/docs/web/server-config-file-template
    server:
      address:     ":8000"
      openapiPath: "/api.json"
      swaggerPath: "/swagger"
    
    # https://goframe.org/docs/core/glog-config
    logger:
      level : "all"
      stdout: true
